# Generated by Django 4.2 on 2024-08-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
